=== BragaMann/DWeb2019/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT PROJECT_RECORD (INFO, WORKTEAM, ABSTRACT, DELIVERABLES, RECORD_DATE) >

<!ELEMENT INFO (KEY_NAME, TITLE, SUBTITLE, BEGIN_DATE, END_DATE, SUPERVISOR) >
    <!ELEMENT KEY_NAME (#PCDATA) >
    <!ELEMENT TITLE (#PCDATA) >
    <!ELEMENT SUBTITLE (#PCDATA) >
    <!ELEMENT BEGIN_DATE (#PCDATA) >
    <!ELEMENT END_DATE (#PCDATA) >
    <!ELEMENT SUPERVISOR (#PCDATA) >

<!ELEMENT WORKTEAM (MEMBER+) >
    <!ELEMENT MEMBER (NAME , EMAIL?) >
    <!ELEMENT NAME (#PCDATA) >
    <!ELEMENT EMAIL (#PCDATA) >

<!ELEMENT ABSTRACT (#PCDATA) >

<!ELEMENT DELIVERABLES (DELIVERABLE+) >
    <!ELEMENT DELIVERABLE (#PCDATA) >

<!ELEMENT RECORD_DATE (#PCDATA) >

<!ATTLIST SUPERVISOR
                    REF CDATA #IMPLIED>
                        
<!ATTLIST EMAIL
                REF CDATA #IMPLIED>
                
<!ATTLIST DELIVERABLE
                REF CDATA #REQUIRED>

=== BragaMann/DWeb2019/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PROJECT_RECORD SYSTEM "PR.dtd">
<PROJECT_RECORD>
    <INFO>
        <KEY_NAME></KEY_NAME>
        <TITLE></TITLE>
        <SUBTITLE></SUBTITLE>
        <BEGIN_DATE></BEGIN_DATE>
        <END_DATE></END_DATE>
        <SUPERVISOR></SUPERVISOR>
    </INFO>
    <WORKTEAM>
        <MEMBER>
            <NAME></NAME>
            <EMAIL></EMAIL>
        </MEMBER>
    </WORKTEAM>
    <ABSTRACT></ABSTRACT>
    <DELIVERABLES>
        <DELIVERABLE REF=""></DELIVERABLE>
    </DELIVERABLES>
    <RECORD_DATE></RECORD_DATE>
</PROJECT_RECORD>
